version: 0.2

phases:
  install:
    commands:
      - .\SetupContainer.ps1
  pre_build:
    commands:
      - mkdir c:\temp
      - mkdir c:\temp\bookmark
      - mkdir signed_artifacts
      - $input_artifacts = (Get-ChildItem Env:CODEBUILD_SRC_DIR_BuildOutput_artifacts).Value
      - Get-ChildItem $input_artifacts -Recurse -filter *.dll | Copy-Item -Destination signed_artifacts
      - Get-ChildItem $input_artifacts -Recurse -filter *.exe | Copy-Item -Destination signed_artifacts
  build:
    commands:
      - nuget restore AWSKinesisTap.sln
      - nuget restore .\KinesisTapMsiBuild.sln
      - dotnet restore AWSKinesisTap.sln
      - dotnet build AWSKinesisTap.sln -c Release
      - msbuild KinesisTapMsiBuild.sln /p:Configuration=Release /p:Platform="x64"
      - dotnet test .\AWSKinesisTap.sln -c Release --filter Category!=Integration
  post_build:
    commands:
      - .\build.ps1 -packageOnly
artifacts:
  files:
    - Amazon.KinesisTap/bin/*.msi
    - Amazon.KinesisTap/bin/*.nupkg
    - Amazon.KinesisTap.Deploy/*
    - Amazon.KinesisTap/Birdwatcher/bin/*.zip
    - Amazon.KinesisTap.CiIntegration.Test/bin/release/*.zip
