version: 0.2

phases:
  install:
    commands:
      - dotnet --list-sdks
      - dotnet --list-runtimes
      - Set-Service -Name wuauserv -StartupType Manual
      - DISM /Online /Enable-Feature:NetFx3 /All /Quiet
      - choco install -y wixtoolset --version 3.11.0.20170506 --no-progress
  pre_build:
    commands:
      - mkdir c:\temp
      - mkdir c:\temp\bookmark
  build:
    commands:
      - nuget restore AWSKinesisTap.sln
      - nuget restore .\KinesisTapMsiBuild.sln
      - dotnet build AWSKinesisTap.sln -c Release
      - dotnet test .\AWSKinesisTap.sln -c Release --filter Category!=Integration
  post_build:
    commands:
      - .\build.ps1
artifacts:
  files:
    - Amazon.KinesisTap/bin/Release/AWSKinesisTap.exe
    - msibuild/Amazon.KinesisTap.*.dll
    - msibuild/*.exe
