version: 0.2

phases:
  install:
    commands:
      - .\SetupContainer.ps1
      - dotnet --list-sdks
      - dotnet --list-runtimes
  pre_build:
    commands:
      - mkdir c:\temp
      - mkdir c:\temp\bookmark
  build:
    commands:
      - nuget restore AWSKinesisTap.sln
      - nuget restore .\KinesisTapMsiBuild.sln
      - dotnet build AWSKinesisTap.sln -c Release
      - msbuild KinesisTapMsiBuild.sln /p:Configuration=Release /p:Platform="x64"
      - dotnet test .\AWSKinesisTap.sln -c Release --filter Category!=Integration
  post_build:
    commands:
      - .\build.ps1 -packageOnly
artifacts:
  files:
    - Amazon.AWSKinesisTap/bin/Release/KinesisTap.exe
    - msibuild/Amazon.AWSKinesisTap.*.dll
    - msibuild/*.exe
  